# @package _global_

# Be careful when using _raw, history
obs:
  use_phase: True
  obs_dict:
    actor_obs: [
      base_ang_vel,
      projected_gravity,
      command_lin_vel,
      command_ang_vel,
      command_stand,
      command_ee,
      dof_pos,
      dof_vel,
      actions,
      command_gait,
      sin_phase,
      cos_phase,
    ]

    critic_obs: [
      base_lin_vel,
      base_ang_vel,
      projected_gravity,
      command_lin_vel,
      command_ang_vel,
      command_stand,
      command_ee,
      dof_pos,
      dof_vel,
      actions,
      end_effector_relative_pos,
      end_effector_gravity,
      command_gait,
      sin_phase,
      cos_phase,
    ]

  history_length:
    actor_obs: 5
    critic_obs: 1
  
  obs_scales: {
    base_lin_vel: 2.0,
    base_ang_vel: 0.25,
    projected_gravity: 1.0,
    command_lin_vel: 1.0,
    command_ang_vel: 1.0,
    command_stand: 1.0,
    command_base_height: 2.0,
    command_ee: 1.0,
    dof_pos: 1.0,
    dof_vel: 0.05,
    actions: 1.0,
    command_gait: 1.0,
    sin_phase: 1.0,
    cos_phase: 1.0,
    end_effector_relative_pos: 1.0,
    end_effector_gravity: 1.0,
  }
  
  add_noise: True

  noise_scales: {
    base_lin_vel: 0.0,
    base_ang_vel: 0.0,
    projected_gravity: 0.00,
    command_lin_vel: 0.0,
    command_ang_vel: 0.0,
    command_stand: 0.0,
    command_base_height: 0.0,
    command_ee: 0.0,
    end_effector_relative_pos: 0.0,
    end_effector_gravity: 0.0,
    command_gait: 0.0,
    dof_pos: 0.01,
    dof_vel: 1.0,
    actions: 0.0,
    sin_phase: 0.0,
    cos_phase: 0.0,
  }

  obs_dims:
    - base_lin_vel: 3
    - base_ang_vel: 3
    - projected_gravity: 3
    - command_lin_vel: 2
    - command_ang_vel: 1
    - command_stand: 1
    - command_base_height: 1
    - command_ee: ${eval:${robot.num_end_effectors} * 5}
    - end_effector_relative_pos: ${eval:${robot.num_end_effectors} * 3}
    - end_effector_gravity: ${eval:${robot.num_end_effectors} * 3}
    - dof_pos: ${robot.dof_obs_size}
    - dof_vel: ${robot.dof_obs_size}
    - actions: ${robot.dof_obs_size} 
    - command_gait: 1
    - sin_phase: 1
    - cos_phase: 1
