# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 13
  dof_obs_size: 12
  actions_dim: 12
  policy_obs_dim: -1 # Jiawei
  critic_obs_dim: -1
  # policy_obs_dim: 45 # Jiawei
  # critic_obs_dim: 238
  # policy_obs_dim: 45 # Jiawei
  # policy_obs_dim: 241 # Jiawei
  # self_obs_max_coords: 298  # ${eval:1+20*(3+6+3+3)-3}

  key_bodies: ["left_ankle_roll_link", "right_ankle_roll_link"]
  contact_bodies: [ "left_ankle_roll_link", "right_ankle_roll_link" ]
  right_foot_name: "right_ankle_roll_link"
  left_foot_name: "left_ankle_roll_link"
  foot_name: "ankle_roll_link"
  knee_name: "knee_link"

  has_upper_body_dof: False
  dof_names: ['left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
              'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint']
  upper_dof_names: []
  lower_dof_names: ['left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
                    'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint']
  dof_pos_lower_limit_list: [-2.35, -0.26, -2.75, -0.33489, -0.68, -0.2618, -2.35, -2.53, -2.75, -0.33489, -0.68, -0.2618]
  dof_pos_upper_limit_list: [3.05, 2.53, 2.75, 2.5449, 0.73, 0.2618, 3.05, 0.26, 2.75, 2.5449, 0.73, 0.2618]
  dof_vel_limit_list: [32.0, 32.0, 32.0, 20.0, 53.0, 53.0, 32.0, 32.0, 32.0, 20.0, 53.0, 53.0]
  dof_effort_limit_list: [88.0, 88.0, 88.0, 139.0, 40.0, 40.0, 88.0, 88.0, 88.0, 139.0, 40.0, 40.0]

  body_names: ['pelvis', 
                'left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link',
                'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link']


  terminate_after_contacts_on : ["pelvis", "shoulder", "hip"]
  penalize_contacts_on: ["hip"]
  init_state:
    pos: [0.0, 0.0, 0.8] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      left_hip_yaw_joint: 0.
      left_hip_roll_joint: 0.
      left_hip_pitch_joint: -0.1
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.
      right_hip_yaw_joint: 0.
      right_hip_roll_joint: 0.
      right_hip_pitch_joint: -0.1
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.
      torso_joint : 0.

  randomize_link_body_names: [
    'pelvis', 'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link',
    'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link',
  ]


  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_yaw: 150
      hip_roll: 150
      hip_pitch: 150
      knee: 300
      ankle: 40

    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_yaw: 2
      hip_roll: 2
      hip_pitch: 2
      knee: 4
      ankle: 2

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "g1/${robot.asset.robot_type}.urdf"
    usd_file: "g1/${robot.asset.robot_type}.usd"
    xml_file: "g1/${robot.asset.robot_type}.xml"
    robot_type: g1_unitree_deprecated
    self_collisions: 1 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3

# Override motion lib default to use the adapted H1 variant
# motion_lib:
#   _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
# env:
#   config:
#     simulator:
#       sim:
#         fps: 200 # 1/dt , dt = 0.005
#         control_freq_inv: 4  # decimation
#         substeps: 1
