# @package _global_

defaults:
  - legged_base

# Env structure
env:
  _target_: humanoidverse.envs.locomotion.locomotion_ma_stand_gait_ee.LeggedRobotLocomotionStanceGaitEETracking
  config:
    max_episode_length_s: 20
    locomotion_obs_scales:
      lin_vel: 1.0
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 1.0
      humanoid_commands_scale: 1.0
    locomotion_command_ranges:
      lin_vel_x: [-1.0, 1.0]
      lin_vel_y: [-1.0, 1.0]
      ang_vel_yaw: [-1.0, 1.0]
      heading: [-3.14, 3.14]
      gait_period: [0.7, 1.1]
      # base_height: [-0.15, 0.0]
    ee_command_ranges:
      right_rubber_hand:
        active_prob: 1.0
        x: [-0.1, 0.1]
        y: [-0.1, 0.1]
        z: [-0.05, 0.15]
        tolerance: [0.1, 0.15]
        offset: [0.3, -0.15, 0.05]
    stand_prob: 0.4
    tapping_in_place_prob: 0.0
    # Upper body waist motion setting
    apply_waist_roll_only_when_stance: True
    apply_waist_pitch_only_when_stance: True
    apply_waist_yaw_only_when_stance: True
    fix_waist_yaw: True
    fix_waist_roll: True
    fix_waist_pitch: True
    fix_waist_yaw_range: [-0.0, 0.0]
    fix_waist_roll_range: [-0.0, 0.0]
    fix_waist_pitch_range: [-0.15, 0.45]
    zero_fix_waist_yaw_prob: 0.5
    zero_fix_waist_roll_prob: 1.0
    zero_fix_waist_pitch_prob: 0.5
    # Upper body motion resampling
    # resample_motion_when_training: True
    # resample_time_interval_s: 2000
    # Locomotion command resampling
    locomotion_command_resampling_time: 10.0
    obs_history:
      history_len: 0

    termination:
      terminate_by_contact: False
      # terminate_by_lin_vel: False
      # terminate_by_ang_vel: False
      terminate_by_gravity: True
      terminate_by_low_height: True
      terminate_when_close_to_dof_pos_limit: False
      terminate_when_close_to_dof_vel_limit: False
      terminate_when_close_to_torque_limit: False
      # terminate_when_motion_end: False
      # terminate_when_low_upper_dof_tracking: False

    termination_scales:
      termination_min_base_height : 0.3
      # termination_max_base_vel : 10.0
      # termination_max_base_ang_vel : 5.0
      termination_gravity_x : 0.8
      termination_gravity_y : 0.8
      termination_close_to_dof_pos_limit : 0.98
      termination_close_to_dof_vel_limit : 0.98
      termination_close_to_torque_limit : 0.98
      terminate_when_low_upper_dof_tracking_threshold: 0.1


# Globally accessible parameters
log_task_name: decoupled_locomotion

eval_overrides:
  env:
    config: 
      max_episode_length_s: 100000
